# Generated by Django 5.2.3 on 2025-06-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Выберите свою страну",
                max_length=100,
                null=True,
                verbose_name="Страна",
            ),
        ),
    ]
