# Generated by Django 5.2.3 on 2025-06-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заглавие поста", verbose_name="Заглавие"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите содержание поста", verbose_name="Содержание"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте фото продукта",
                        null=True,
                        upload_to="BlogPosts-preview",
                        verbose_name="Фото",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("is_published", models.BooleanField()),
                (
                    "views",
                    models.IntegerField(
                        help_text="Количество просмотров",
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["title", "views", "is_published", "created_at"],
            },
        ),
    ]
