# Generated by Django 5.2.3 on 2025-06-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="views",
            field=models.IntegerField(
                default=0,
                help_text="Количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
