# Generated by Django 5.2.3 on 2025-06-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                help_text="Нажмите, если хотите опубликовать пост",
                verbose_name="Статус опубликования",
            ),
        ),
    ]
