# Generated by Django 5.2.3 on 2025-06-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Нажмите, если хотите опубликовать пост",
                verbose_name="Статус опубликования",
            ),
        ),
    ]
