# Generated by Django 4.2.2 on 2025-06-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_products_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Укажите данный параметр, если хотите опубликовать товар",
                verbose_name="Статус публикации",
            ),
        ),
    ]
